name: olimpica
channels:
  - conda-forge
dependencies:
  - python=3.6
  - jupyterlab=1.2.*
  - scipy=1.3.*
  - numpy=1.17.*
  - pandas=0.25.*
  - pyhamcrest=1.9.*
  - matplotlib=3.1.*
  - tqdm
  - sphinx
  - xlrd=1.2.*
  - pyprind=2.11.*
  - pulp=1.6.*
  - openpyxl
  - pip=19.**
  - pip:
      - pyyaml
      - sphinx_redactor_theme
      - sphinx_press_theme
      - mip=1.8.1